repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, black]
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        exclude: ^migrations/
        args: [--max-line-length, "120"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.982" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        exclude: app/config.py
        args: [--ignore-missing-imports, --follow-imports, skip]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.24.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
