"""added unit to pet model

Revision ID: 9f4e9ab8f480
Revises: 71455eacee4d
Create Date: 2021-11-24 18:33:35.475146

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f4e9ab8f480"
down_revision = "71455eacee4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pets", sa.Column("unit", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pets", "unit")
    # ### end Alembic commands ###
