"""changed pet model to have goals instead of age and neutered

Revision ID: 52e74d1d229e
Revises: b0bbcf0ccab0
Create Date: 2021-10-26 10:58:17.732042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e74d1d229e'
down_revision = 'b0bbcf0ccab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('goal', sa.String(), nullable=False))
    op.drop_column('pets', 'age')
    op.drop_column('pets', 'neutered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('neutered', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pets', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pets', 'goal')
    # ### end Alembic commands ###
