"""added char limit to image_url

Revision ID: 9dec85b2547c
Revises: 154e81c63e2d
Create Date: 2021-11-12 17:41:52.062120

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9dec85b2547c"
down_revision = "154e81c63e2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pets", "image_url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pets", sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
