"""created food model

Revision ID: 4a199ce6262a
Revises: bbb60b634a0f
Create Date: 2021-10-21 09:19:48.410539

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a199ce6262a"
down_revision = "bbb60b634a0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "foods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("food_name", sa.String(length=100), nullable=False),
        sa.Column("food_type", sa.String(length=100), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("foods")
    # ### end Alembic commands ###
