"""added serving size column to food model

Revision ID: 1a609501f3f7
Revises: b260530df709
Create Date: 2021-10-21 14:18:34.286696

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1a609501f3f7"
down_revision = "b260530df709"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("foods", sa.Column("serving_size", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("foods", "serving_size")
    # ### end Alembic commands ###
