"""added first and last name to user model

Revision ID: e4ec687f0e20
Revises: ffdc0a98111c
Create Date: 2021-10-19 10:14:19.677967

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e4ec687f0e20"
down_revision = "ffdc0a98111c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("firstname", sa.String(length=40), nullable=False))
    op.add_column("users", sa.Column("lastname", sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, "users", ["lastname"])
    op.create_unique_constraint(None, "users", ["firstname"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "lastname")
    op.drop_column("users", "firstname")
    # ### end Alembic commands ###
