"""added char limit to image_url

Revision ID: 71455eacee4d
Revises: 9dec85b2547c
Create Date: 2021-11-12 17:42:04.912572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71455eacee4d'
down_revision = '9dec85b2547c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'image_url')
    # ### end Alembic commands ###
