"""added dates in database models food, meals, pet_weights and route

Revision ID: b0bbcf0ccab0
Revises: ca2606ec5782
Create Date: 2021-10-22 16:24:51.917880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0bbcf0ccab0'
down_revision = 'ca2606ec5782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('meals', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('pet_weights', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet_weights', 'created_at')
    op.drop_column('meals', 'created_at')
    op.drop_column('foods', 'created_at')
    # ### end Alembic commands ###
