"""added image_url to pet model

Revision ID: 154e81c63e2d
Revises: b148664a8657
Create Date: 2021-11-12 17:39:47.977926

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "154e81c63e2d"
down_revision = "b148664a8657"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pets", sa.Column("image_url", sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pets", "image_url")
    # ### end Alembic commands ###
