"""added foreign key of user id to pets model

Revision ID: 08498dca2209
Revises: cc3aef0ae753
Create Date: 2021-10-19 14:45:05.923144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08498dca2209'
down_revision = 'cc3aef0ae753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    # ### end Alembic commands ###
