"""added first and last name to user model, and removed unique constraints on names

Revision ID: 39622e80115f
Revises: e4ec687f0e20
Create Date: 2021-10-19 10:22:17.606367

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39622e80115f"
down_revision = "e4ec687f0e20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_firstname_key", "users", type_="unique")
    op.drop_constraint("users_lastname_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_lastname_key", "users", ["lastname"])
    op.create_unique_constraint("users_firstname_key", "users", ["firstname"])
    # ### end Alembic commands ###
