"""changed length of pet name and food name

Revision ID: b148664a8657
Revises: fd20575935b5
Create Date: 2021-10-29 08:18:49.781784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b148664a8657'
down_revision = 'fd20575935b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('food_name', sa.String(length=40), nullable=False))
    op.add_column('pets', sa.Column('name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'name')
    op.drop_column('foods', 'food_name')
    # ### end Alembic commands ###
