"""created Meal model, and only has relationship with pets and not with food

Revision ID: b260530df709
Revises: 4a199ce6262a
Create Date: 2021-10-21 09:44:23.209959

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b260530df709"
down_revision = "4a199ce6262a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["foods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meals")
    # ### end Alembic commands ###
