"""added relationship between meal and food to allow cascade delete from food to meal

Revision ID: 5fb6a34bf8dd
Revises: 862226a3f545
Create Date: 2021-10-26 16:25:37.016433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb6a34bf8dd'
down_revision = '862226a3f545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'created_at')
    # ### end Alembic commands ###
