"""commented in neutered field in pets to force changes

Revision ID: 1233fbba4a92
Revises: 11fa0707cd90
Create Date: 2021-10-20 15:18:59.785977

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1233fbba4a92"
down_revision = "11fa0707cd90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pets", sa.Column("neutered", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pets", "neutered")
    # ### end Alembic commands ###
