"""changed length of pet name and food name

Revision ID: fd20575935b5
Revises: 5fb6a34bf8dd
Create Date: 2021-10-29 08:18:32.044756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd20575935b5'
down_revision = '5fb6a34bf8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'food_name')
    op.drop_column('pets', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('food_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
