"""added calorie count per meal to model

Revision ID: 02fe94aebacb
Revises: 8ee103345189
Create Date: 2021-12-27 15:45:31.193026

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02fe94aebacb"
down_revision = "8ee103345189"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meals", sa.Column("calories", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meals", "calories")
    # ### end Alembic commands ###
