"""created pets model

Revision ID: cc3aef0ae753
Revises: 39622e80115f
Create Date: 2021-10-19 13:00:10.044036

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc3aef0ae753"
down_revision = "39622e80115f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("current_weight", sa.Float(), nullable=False),
        sa.Column("ideal_weight", sa.Float(), nullable=False),
        sa.Column("neutered", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pets")
    # ### end Alembic commands ###
